# Site settings
title: Zachary I. Schutzman
email: ianzach@seas.upenn.edu
description: > # this means to ignore newlines until "baseurl:"
 I do math and computers
# baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://www.zachschutzman.com" # the base hostname & protocol for your site
twitter_username: zschutzy
github_username:  zschutzman
permalink: /blog/:year/:month/:title.html
gems:
  - jekyll-sitemap

# Build settings
markdown: kramdown
theme: minima
shortbio: Zach is a PhD student at the University of Pennsylvania, Department of Computer and Information Science.  His research interests include game theory and mechanism design, machine learning, and computing for the social sciences.

tag_page_layout: tag_page
tag_page_dir: tag

tag_feed_layout: tag_feed
tag_feed_dir: tag

tag_permalink_style: pretty
